---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-mongodb-operator
  labels:
    control-plane: open-mongodb-operator
spec:
  selector:
    matchLabels:
      control-plane: open-mongodb-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: open-mongodb-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        env:
          - name: LOCAL_REGISTRY
            value: {{ .Values.localRegistry | default "docker.io" }}
          - name: NAMESPACE_OVERRIDE
            value: {{ .Values.namespaceOverride | default "radondb" }}
          - name: DEFAULT_MONGODB_IMAGE
            value: {{ .Values.cluster.mongodb.image }}
          - name: DEFAULT_MONGODB_VERSION
            value: {{ .Values.cluster.mongodb.version }}
          - name: DEFAULT_EXPORTER_IMAGE
            value: {{ .Values.cluster.exporter.image }}
          - name: DEFAULT_EXPORTER_VERSION
            value: {{ .Values.cluster.exporter.version }}
          - name: LOG_FORMAT
            value: {{ .Values.logFormat | default "plaintext" }}
        image: "{{ .Values.localRegistry | default "docker.io" }}{{"/"}}{{ .Values.namespaceOverride | default "radondb" }}{{"/"}}{{ .Values.manager.image }}:{{ .Values.manager.tag | default .Chart.AppVersion }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.manager.resources | nindent 12 }}
      serviceAccountName: open-mongodb-operator
      terminationGracePeriodSeconds: 10
