apiVersion: v1
data:
  password: {{ .Values.prometheus.username }}
  username: {{ .Values.prometheus.password }}
kind: Secret
metadata:
  name: {{ .Values.prometheus.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
---
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/vendor: kubesphere
  name: open-mongodb-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      scheme: http
      basicAuth:
        password:
          key: password
          name: {{ .Release.prometheus.secretName }}
        username:
          key: username
          name: {{ .Release.prometheus.secretName }}
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      mongodbv2/exporter-monitor: "yes"
