---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-mongodb-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-mongodb-operator-role
subjects:
- kind: ServiceAccount
  name: open-mongodb-operator
  namespace: {{ .Release.Namespace }}
